In [292]:
import pandas as pd 
import numpy as np

In [293]:
ratings = pd.read_csv('../Data/final_rating_not_spare.csv', usecols=['customer_id', 'product_id', 'stars'])
ratings.head()

   product_id  customer_id  stars
0        9672        53270      5
1        9672        91213      4
2        3038        56289      5
3        3038        88524      5
4        3038        72126      5

In [294]:
ratings['customer_id'].min()

33

In [295]:
customer_index = np.unique(ratings['customer_id'])
customer_index = np.sort(customer_index)
ratings['id_customer'] = ratings['customer_id'].apply(lambda x: np.where(customer_index==int(x))[0][0])

In [296]:
ratings.drop('customer_id', axis=1, inplace=True)
ratings.rename(columns={'id_customer': 'customer_id'}, inplace=True)

1382

In [297]:
len_ratings = ratings.shape
len_ratings

(20849, 3)

In [298]:
split = int((0.8*len_ratings[0]))
split

16679

In [299]:
# rate_train = ratings.loc[:split, :].to_numpy()
# rate_test = ratings.loc[split:, :].to_numpy()
# rate_train.shape

In [300]:
items = pd.read_csv('../Data/final_all_clean_books.csv')
items.head()

,id,sku,name,url_path,book_cover,short_description,price,list_price,price_usd,discount,...,thumbnail_url,productset_group_name,description,publisher,authors,stock_item,big_category,sub_category,clean_description,new_id
0,58390336,3380735508079,Python cơ bản,python-co-ban-p58390336.html?spid=58390337,Bìa mềm,SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...,125000,125000,5.343,0,...,https://salt.tikicdn.com/cache/280x280/ts/prod...,"Sách Công Nghệ Thông Tin, Lập Trình",SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...,NXB Đại Học Quốc Gia Hà Nội,Bùi Việt Hà,5.0,Sách Công Nghệ Thông Tin,Lập Trình,sách python cơ_bản ngôn_ngữ lập_trình bậc pyth...,9649
1,1664525,2147399986992,Giáo Trình Kỹ Thuật Lập Trình C Căn Bản Và Nân...,giao-trinh-ky-thuat-lap-trinh-c-can-ban-va-nan...,Bìa mềm,Giáo trình kỹ thuật lập trình C căn bản và nân...,67500,135000,2.885,67500,...,https://salt.tikicdn.com/cache/280x280/ts/prod...,"Sách Công Nghệ Thông Tin, Lập Trình",Giáo trình kỹ thuật lập trình C căn bản và nân...,Huy Hoàng Bookstore,Nhiều Tác Giả,801.0,Sách Công Nghệ Thông Tin,Lập Trình,giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...,2371
2,55573620,6752050391860,Giáo Trình Tự Học AutoCAD 2019 Thực Hành Bằng ...,giao-trinh-tu-hoc-autocad-2019-thuc-hanh-bang-...,Bìa mềm,Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...,110000,110000,4.702,0,...,https://salt.tikicdn.com/cache/280x280/ts/prod...,"Sách Công Nghệ Thông Tin, Thiết Kế - Đồ Họa",Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...,Công Ty TNHH Văn Hóa - Thế Giới Sách Việt,Nhiều Tác Giả,12.0,Sách Công Nghệ Thông Tin,Thiết Kế - Đồ Họa,mục_lục chương autocad chương kỹ_năng cơ_bản c...,9114
3,24889348,3747885152000,Lập trình hướng đối tượng JAVA core dành cho n...,lap-trinh-huong-doi-tuong-java-core-danh-cho-n...,NaN,I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...,189000,299000,8.079,110000,...,https://salt.tikicdn.com/cache/280x280/ts/prod...,"Sách Công Nghệ Thông Tin, Lập Trình",I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...,-,Nhiều Tác Giả,NaN,Sách Công Nghệ Thông Tin,Lập Trình,đôi tác_giả neos thành nguyễn văn thành lập_tr...,6180
4,37667006,5950833882104,Combo Giáo Trình Kỹ Thuật Lập Trình C Căn Bản ...,combo-giao-trinh-ky-thuat-lap-trinh-c-can-ban-...,Bìa mềm,Giáo trình kỹ thuật lập trình C căn bản và nân...,223400,280000,9.550,56600,...,https://salt.tikicdn.com/cache/280x280/ts/prod...,"Sách Công Nghệ Thông Tin, Lập Trình",Giáo trình kỹ thuật lập trình C căn bản và nân...,Huy Hoàng Bookstore,Nhiều Tác Giả,97.0,Sách Công Nghệ Thông Tin,Lập Trình,giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...,7125

In [301]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10330 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     10330 non-null  int64
 1   sku                    10330 non-null  int64
 2   name                   10330 non-null  object
 3   url_path               10330 non-null  object
 4   book_cover             9417 non-null   object
 5   short_description      10327 non-null  object
 6   price                  10330 non-null  int64
 7   list_price             10330 non-null  int64
 8   price_usd              10330 non-null  float64
 9   discount               10330 non-null  int64
 10  discount_rate          10330 non-null  int64
 11  rating_average         10330 non-null  float64
 12  review_count           10330 non-null  int64
 13  order_count            10330 non-null  int64
 14  favourite_count        10330 non-null  int64
 15  thumbnail_url          10330 non-null  object
 16  productset_group_name  10330 non-null  object
 17  description            10326 non-null  object
 18  publisher              10323 non-null  object
 19  authors                10323 non-null  object
 20  stock_item             8981 non-null   float64
 21  big_category           10330 non-null  object
 22  sub_category           10330 non-null  object
 23  clean_description      10320 non-null  object
 24  new_id                 10330 non-null  int64
dtypes: float64(3), int64(10), object(12)
memory usage: 2.0+ MB

In [302]:
n_items = items.shape[0]
n_items

10330

In [303]:
# X0 = items.to_numpy()
# X_train_counts = X0[:, 23:24]

In [304]:
items.dropna(axis=0, subset=['clean_description'], inplace=True)

In [305]:
items_index = np.unique(items['new_id'])
items_index = np.sort(items_index)
items['id_new'] = items['new_id'].apply(lambda x: np.where(items_index==int(x))[0][0])

In [306]:
items.drop('new_id', axis=1, inplace=True)
items.rename(columns={'id_new': 'new_id'}, inplace=True)

In [307]:
def format_id(id_):
    try:
        return np.where(items_index==id_)[0][0]
    except:
        return -1

In [308]:
ratings['new_product_id'] = ratings['product_id'].apply(lambda x: format_id(int(x)))

In [309]:
ratings.drop('product_id', axis=1, inplace=True)
ratings.rename(columns={'new_product_id': 'product_id'}, inplace=True)

In [310]:
drop_idx = ratings[ratings['product_id']==-1].index

In [311]:
ratings.drop(drop_idx, inplace=True)

In [312]:
n_user = np.unique(ratings['customer_id'])
n_users = len(n_user)
n_users

1382

In [313]:
# rate_test[:, 1]

In [314]:
# len(np.unique(rate_train[:, 1]))

In [315]:
# len(np.unique(rate_test[:, 1]))

In [316]:
items.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10320 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     10320 non-null  int64
 1   sku                    10320 non-null  int64
 2   name                   10320 non-null  object
 3   url_path               10320 non-null  object
 4   book_cover             9409 non-null   object
 5   short_description      10320 non-null  object
 6   price                  10320 non-null  int64
 7   list_price             10320 non-null  int64
 8   price_usd              10320 non-null  float64
 9   discount               10320 non-null  int64
 10  discount_rate          10320 non-null  int64
 11  rating_average         10320 non-null  float64
 12  review_count           10320 non-null  int64
 13  order_count            10320 non-null  int64
 14  favourite_count        10320 non-null  int64
 15  thumbnail_url          10320 non-null  object
 16  productset_group_name  10320 non-null  object
 17  description            10320 non-null  object
 18  publisher              10319 non-null  object
 19  authors                10319 non-null  object
 20  stock_item             8975 non-null   float64
 21  big_category           10320 non-null  object
 22  sub_category           10320 non-null  object
 23  clean_description      10320 non-null  object
 24  new_id                 10320 non-null  int64
dtypes: float64(3), int64(10), object(12)
memory usage: 2.0+ MB

In [317]:
items[items['new_id']==10326]['clean_description']

Series([], Name: clean_description, dtype: object)

In [318]:
from sklearn.model_selection import train_test_split
rate_train, rate_test = train_test_split(ratings.values, test_size=0.2, random_state=43)

In [319]:
from sklearn.feature_extraction.text import TfidfVectorizer
transformer = TfidfVectorizer()
tfidf = transformer.fit_transform(items['clean_description'])

In [320]:
def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id
    """
    y = rate_matrix[:, 1] # all users
    # print(y)
    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1 
    # while index in python starts from 0
    ids = np.where(y == user_id)[0] 
    # print(ids)
    item_ids = rate_matrix[ids, 2] # index starts from 0 
    # print(item_ids)
    scores = rate_matrix[ids, 0]
    # print(scores)
    return (item_ids, scores)

In [321]:
ratings[ratings['customer_id']==1381]

      stars  customer_id  product_id
3378      5         1381        7212
4362      5         1381        9099
4472      5         1381        9229
4484      5         1381        8967
4586      5         1381        8828
4627      5         1381        8483
4669      2         1381        9089
4685      5         1381        9355
4779      5         1381        9479
5061      5         1381        8278
5161      5         1381        9883
5193      5         1381        8121
5426      5         1381       10046
5627      5         1381       10282
5681      5         1381       10194

In [322]:
rate_train[140, :]

array([   5, 1381, 9229], dtype=int64)

In [323]:
get_items_rated_by_user(rate_test, 10)

(array([5682, 6729, 8266, 2908, 7435, 2978], dtype=int64),
 array([5, 5, 5, 5, 5, 5], dtype=int64))

In [324]:
rate_test[245, :]

array([   5,   10, 5682], dtype=int64)

In [325]:
ratings.head()

   stars  customer_id  product_id
0      5          571        9664
1      4          990        9664
2      5          607        3038
3      5          958        3038
4      5          767        3038

In [326]:
ids, scores = get_items_rated_by_user(rate_train, 1381)
print(ids)
scores

[ 9229  9099  7212  9089  9479  8278  9355  8483  8121  8967 10046]

array([5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [327]:
rate_train

array([[   5,  318, 9637],
       [   5,  758, 7053],
       [   5,  592, 4513],
       ...,
       [   5,  946, 9773],
       [   5,  509,  913],
       [   5, 1179, 7765]], dtype=int64)

In [328]:
tfidf.shape

(10320, 37795)

In [329]:
tfidf[10122, :]

<1x37795 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [330]:
from sklearn.linear_model import RidgeCV
from sklearn import linear_model
from sklearn.svm import SVR

d = tfidf.shape[1] # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))

for n in range(n_users):
    print(f"User {n}")  
    # ids, scores = get_items_rated_by_user(rate_train, n)
    # clf = Ridge(alpha=0.01, fit_intercept=True)
    clf = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1], cv=5)
    # clf = linear_model.LinearRegression()
    # clf = SVR()
    Xhat = tfidf[ids, :]
    
    clf.fit(Xhat, scores) 
    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_

User 0
User 1
User 2
User 3
User 4
User 5
User 6
User 7
User 8
User 9
User 10
User 11
User 12
User 13
User 14
User 15
User 16
User 17
User 18
User 19
User 20
User 21
User 22
User 23
User 24
User 25
User 26
User 27
User 28
User 29
User 30
User 31
User 32
User 33
User 34
User 35
User 36
User 37
User 38
User 39
User 40
User 41
User 42
User 43
User 44
User 45
User 46
User 47
User 48
User 49
User 50
User 51
User 52
User 53
User 54
User 55
User 56
User 57
User 58
User 59
User 60
User 61
User 62
User 63
User 64
User 65
User 66
User 67
User 68
User 69
User 70
User 71
User 72
User 73
User 74
User 75
User 76
User 77
User 78
User 79
User 80
User 81
User 82
User 83
User 84
User 85
User 86
User 87
User 88
User 89
User 90
User 91
User 92
User 93
User 94
User 95
User 96
User 97
User 98
User 99
User 100
User 101
User 102
User 103
User 104
User 105
User 106
User 107
User 108
User 109
User 110
User 111
User 112
User 113
User 114
User 115
User 116
User 117
User 118
User 119
User 120
User 121
User 122
User 123
User 124
User 125
User 126
User 127
User 128
User 129
User 130
User 131
User 132
User 133
User 134
User 135
User 136
User 137
User 138
User 139
User 140
User 141
User 142
User 143
User 144
User 145
User 146
User 147
User 148
User 149
User 150
User 151
User 152
User 153
User 154
User 155
User 156
User 157
User 158
User 159
User 160
User 161
User 162
User 163
User 164
User 165
User 166
User 167
User 168
User 169
User 170
User 171
User 172
User 173
User 174
User 175
User 176
User 177
User 178
User 179
User 180
User 181
User 182
User 183
User 184
User 185
User 186
User 187
User 188
User 189
User 190
User 191
User 192
User 193
User 194
User 195
User 196
User 197
User 198
User 199
User 200
User 201
User 202
User 203
User 204
User 205
User 206
User 207
User 208
User 209
User 210
User 211
User 212
User 213
User 214
User 215
User 216
User 217
User 218
User 219
User 220
User 221
User 222
User 223
User 224
User 225
User 226
User 227
User 228
User 229
User 230
User 231
User 232
User 233
User 234
User 235
User 236
User 237
User 238
User 239
User 240
User 241
User 242
User 243
User 244
User 245
User 246
User 247
User 248
User 249
User 250
User 251
User 252
User 253
User 254
User 255
User 256
User 257
User 258
User 259
User 260
User 261
User 262
User 263
User 264
User 265
User 266
User 267
User 268
User 269
User 270
User 271
User 272
User 273
User 274
User 275
User 276
User 277
User 278
User 279
User 280
User 281
User 282
User 283
User 284
User 285
User 286
User 287
User 288
User 289
User 290
User 291
User 292
User 293
User 294
User 295
User 296
User 297
User 298
User 299
User 300
User 301
User 302
User 303
User 304
User 305
User 306
User 307
User 308
User 309
User 310
User 311
User 312
User 313
User 314
User 315
User 316
User 317
User 318
User 319
User 320
User 321
User 322
User 323
User 324
User 325
User 326
User 327
User 328
User 329
User 330
User 331
User 332
User 333
User 334
User 335
User 336
User 337
User 338
User 339
User 340
User 341
User 342
User 343
User 344
User 345
User 346
User 347
User 348
User 349
User 350
User 351
User 352
User 353
User 354
User 355
User 356
User 357
User 358
User 359
User 360
User 361
User 362
User 363
User 364
User 365
User 366
User 367
User 368
User 369
User 370
User 371
User 372
User 373
User 374
User 375
User 376
User 377
User 378
User 379
User 380
User 381
User 382
User 383
User 384
User 385
User 386
User 387
User 388
User 389
User 390
User 391
User 392
User 393
User 394
User 395
User 396
User 397
User 398
User 399
User 400
User 401
User 402
User 403
User 404
User 405
User 406
User 407
User 408
User 409
User 410
User 411
User 412
User 413
User 414
User 415
User 416
User 417
User 418
User 419
User 420
User 421
User 422
User 423
User 424
User 425
User 426
User 427
User 428
User 429
User 430
User 431
User 432
User 433
User 434
User 435
User 436
User 437
User 438
User 439
User 440
User 441
User 442
User 443
User 444
User 445
User 446
User 447
User 448
User 449
User 450
User 451
User 452
User 453
User 454
User 455
User 456
User 457
User 458
User 459
User 460
User 461
User 462
User 463
User 464
User 465
User 466
User 467
User 468
User 469
User 470
User 471
User 472
User 473
User 474
User 475
User 476
User 477
User 478
User 479
User 480
User 481
User 482
User 483
User 484
User 485
User 486
User 487
User 488
User 489
User 490
User 491
User 492
User 493
User 494
User 495
User 496
User 497
User 498
User 499
User 500
User 501
User 502
User 503
User 504
User 505
User 506
User 507
User 508
User 509
User 510
User 511
User 512
User 513
User 514
User 515
User 516
User 517
User 518
User 519
User 520
User 521
User 522
User 523
User 524
User 525
User 526
User 527
User 528
User 529
User 530
User 531
User 532
User 533
User 534
User 535
User 536
User 537
User 538
User 539
User 540
User 541
User 542
User 543
User 544
User 545
User 546
User 547
User 548
User 549
User 550
User 551
User 552
User 553
User 554
User 555
User 556
User 557
User 558
User 559
User 560
User 561
User 562
User 563
User 564
User 565
User 566
User 567
User 568
User 569
User 570
User 571
User 572
User 573
User 574
User 575
User 576
User 577
User 578
User 579
User 580
User 581
User 582
User 583
User 584
User 585
User 586
User 587
User 588
User 589
User 590
User 591
User 592
User 593
User 594
User 595
User 596
User 597
User 598
User 599
User 600
User 601
User 602
User 603
User 604
User 605
User 606
User 607
User 608
User 609
User 610
User 611
User 612
User 613
User 614
User 615
User 616
User 617
User 618
User 619
User 620
User 621
User 622
User 623
User 624
User 625
User 626
User 627
User 628
User 629
User 630
User 631
User 632
User 633
User 634
User 635
User 636
User 637
User 638
User 639
User 640
User 641
User 642
User 643
User 644
User 645
User 646
User 647
User 648
User 649
User 650
User 651
User 652
User 653
User 654
User 655
User 656
User 657
User 658
User 659
User 660
User 661
User 662
User 663
User 664
User 665
User 666
User 667
User 668
User 669
User 670
User 671
User 672
User 673
User 674
User 675
User 676
User 677
User 678
User 679
User 680
User 681
User 682
User 683
User 684
User 685
User 686
User 687
User 688
User 689
User 690
User 691
User 692
User 693
User 694
User 695
User 696
User 697
User 698
User 699
User 700
User 701
User 702
User 703
User 704
User 705
User 706
User 707
User 708
User 709
User 710
User 711
User 712
User 713
User 714
User 715
User 716
User 717
User 718
User 719
User 720
User 721
User 722
User 723
User 724
User 725
User 726
User 727
User 728
User 729
User 730
User 731
User 732
User 733
User 734
User 735
User 736
User 737
User 738
User 739
User 740
User 741
User 742
User 743
User 744
User 745
User 746
User 747
User 748
User 749
User 750
User 751
User 752
User 753
User 754
User 755
User 756
User 757
User 758
User 759
User 760
User 761
User 762
User 763
User 764
User 765
User 766
User 767
User 768
User 769
User 770
User 771
User 772
User 773
User 774
User 775
User 776
User 777
User 778
User 779
User 780
User 781
User 782
User 783
User 784
User 785
User 786
User 787
User 788
User 789
User 790
User 791
User 792
User 793
User 794
User 795
User 796
User 797
User 798
User 799
User 800
User 801
User 802
User 803
User 804
User 805
User 806
User 807
User 808
User 809
User 810
User 811
User 812
User 813
User 814
User 815
User 816
User 817
User 818
User 819
User 820
User 821
User 822
User 823
User 824
User 825
User 826
User 827
User 828
User 829
User 830
User 831
User 832
User 833
User 834
User 835
User 836
User 837
User 838
User 839
User 840
User 841
User 842
User 843
User 844
User 845
User 846
User 847
User 848
User 849
User 850
User 851
User 852
User 853
User 854
User 855
User 856
User 857
User 858
User 859
User 860
User 861
User 862
User 863
User 864
User 865
User 866
User 867
User 868
User 869
User 870
User 871
User 872
User 873
User 874
User 875
User 876
User 877
User 878
User 879
User 880
User 881
User 882
User 883
User 884
User 885
User 886
User 887
User 888
User 889
User 890
User 891
User 892
User 893
User 894
User 895
User 896
User 897
User 898
User 899
User 900
User 901
User 902
User 903
User 904
User 905
User 906
User 907
User 908
User 909
User 910
User 911
User 912
User 913
User 914
User 915
User 916
User 917
User 918
User 919
User 920
User 921
User 922
User 923
User 924
User 925
User 926
User 927
User 928
User 929
User 930
User 931
User 932
User 933
User 934
User 935
User 936
User 937
User 938
User 939
User 940
User 941
User 942
User 943
User 944
User 945
User 946
User 947
User 948
User 949
User 950
User 951
User 952
User 953
User 954
User 955
User 956
User 957
User 958
User 959
User 960
User 961
User 962
User 963
User 964
User 965
User 966
User 967
User 968
User 969
User 970
User 971
User 972
User 973
User 974
User 975
User 976
User 977
User 978
User 979
User 980
User 981
User 982
User 983
User 984
User 985
User 986
User 987
User 988
User 989
User 990
User 991
User 992
User 993
User 994
User 995
User 996
User 997
User 998
User 999
User 1000
User 1001
User 1002
User 1003
User 1004
User 1005
User 1006
User 1007
User 1008
User 1009
User 1010
User 1011
User 1012
User 1013
User 1014
User 1015
User 1016
User 1017
User 1018
User 1019
User 1020
User 1021
User 1022
User 1023
User 1024
User 1025
User 1026
User 1027
User 1028
User 1029
User 1030
User 1031
User 1032
User 1033
User 1034
User 1035
User 1036
User 1037
User 1038
User 1039
User 1040
User 1041
User 1042
User 1043
User 1044
User 1045
User 1046
User 1047
User 1048
User 1049
User 1050
User 1051
User 1052
User 1053
User 1054
User 1055
User 1056
User 1057
User 1058
User 1059
User 1060
User 1061
User 1062
User 1063
User 1064
User 1065
User 1066
User 1067
User 1068
User 1069
User 1070
User 1071
User 1072
User 1073
User 1074
User 1075
User 1076
User 1077
User 1078
User 1079
User 1080
User 1081
User 1082
User 1083
User 1084
User 1085
User 1086
User 1087
User 1088
User 1089
User 1090
User 1091
User 1092
User 1093
User 1094
User 1095
User 1096
User 1097
User 1098
User 1099
User 1100
User 1101
User 1102
User 1103
User 1104
User 1105
User 1106
User 1107
User 1108
User 1109
User 1110
User 1111
User 1112
User 1113
User 1114
User 1115
User 1116
User 1117
User 1118
User 1119
User 1120
User 1121
User 1122
User 1123
User 1124
User 1125
User 1126
User 1127
User 1128
User 1129
User 1130
User 1131
User 1132
User 1133
User 1134
User 1135
User 1136
User 1137
User 1138
User 1139
User 1140
User 1141
User 1142
User 1143
User 1144
User 1145
User 1146
User 1147
User 1148
User 1149
User 1150
User 1151
User 1152
User 1153
User 1154
User 1155
User 1156
User 1157
User 1158
User 1159
User 1160
User 1161
User 1162
User 1163
User 1164
User 1165
User 1166
User 1167
User 1168
User 1169
User 1170
User 1171
User 1172
User 1173
User 1174
User 1175
User 1176
User 1177
User 1178
User 1179
User 1180
User 1181
User 1182
User 1183
User 1184
User 1185
User 1186
User 1187
User 1188
User 1189
User 1190
User 1191
User 1192
User 1193
User 1194
User 1195
User 1196
User 1197
User 1198
User 1199
User 1200
User 1201
User 1202
User 1203
User 1204
User 1205
User 1206
User 1207
User 1208
User 1209
User 1210
User 1211
User 1212
User 1213
User 1214
User 1215
User 1216
User 1217
User 1218
User 1219
User 1220
User 1221
User 1222
User 1223
User 1224
User 1225
User 1226
User 1227
User 1228
User 1229
User 1230
User 1231
User 1232
User 1233
User 1234
User 1235
User 1236
User 1237
User 1238
User 1239
User 1240
User 1241
User 1242
User 1243
User 1244
User 1245
User 1246
User 1247
User 1248
User 1249
User 1250
User 1251
User 1252
User 1253
User 1254
User 1255
User 1256
User 1257
User 1258
User 1259
User 1260
User 1261
User 1262
User 1263
User 1264
User 1265
User 1266
User 1267
User 1268
User 1269
User 1270
User 1271
User 1272
User 1273
User 1274
User 1275
User 1276
User 1277
User 1278
User 1279
User 1280
User 1281
User 1282
User 1283
User 1284
User 1285
User 1286
User 1287
User 1288
User 1289
User 1290
User 1291
User 1292
User 1293
User 1294
User 1295
User 1296
User 1297
User 1298
User 1299
User 1300
User 1301
User 1302
User 1303
User 1304
User 1305
User 1306
User 1307
User 1308
User 1309
User 1310
User 1311
User 1312
User 1313
User 1314
User 1315
User 1316
User 1317
User 1318
User 1319
User 1320
User 1321
User 1322
User 1323
User 1324
User 1325
User 1326
User 1327
User 1328
User 1329
User 1330
User 1331
User 1332
User 1333
User 1334
User 1335
User 1336
User 1337
User 1338
User 1339
User 1340
User 1341
User 1342
User 1343
User 1344
User 1345
User 1346
User 1347
User 1348
User 1349
User 1350
User 1351
User 1352
User 1353
User 1354
User 1355
User 1356
User 1357
User 1358
User 1359
User 1360
User 1361
User 1362
User 1363
User 1364
User 1365
User 1366
User 1367
User 1368
User 1369
User 1370
User 1371
User 1372
User 1373
User 1374
User 1375
User 1376
User 1377
User 1378
User 1379
User 1380
User 1381

In [331]:
# predicted scores
Yhat = tfidf.dot(W) + b

In [332]:
Yhat.shape

(10320, 1382)

In [333]:
Yhat[10]

array([4.73, 4.73, 4.73, ..., 4.73, 4.73, 4.73])

In [334]:
len(Yhat[10])

1382

In [335]:
rate_test

array([[   5,  251, 9283],
       [   5, 1360, 1361],
       [   5,  116, 8521],
       ...,
       [   5, 1085, 8053],
       [   5,  206, 5132],
       [   5,  922, 8708]], dtype=int64)

In [336]:
n = 98
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[2383  713 2147] [3 3 2]
Rated movies ids : [2383  713 2147]
True ratings     : [3 3 2]
Predicted ratings: [4.75 4.74 4.72]

In [337]:
n = 325
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[201 570 949 275] [5 4 5 5]
Rated movies ids : [201 570 949 275]
True ratings     : [5 4 5 5]
Predicted ratings: [4.74 4.72 4.76 4.73]

In [338]:
n = 120
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[7754 8197] [5 5]
Rated movies ids : [7754 8197]
True ratings     : [5 5]
Predicted ratings: [4.81 4.75]

In [339]:
from math import sqrt
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size 
    return sqrt(se/cnt)

print('RMSE for training:', evaluate(Yhat, rate_train, W, b))
print('RMSE for test    :', evaluate(Yhat, rate_test, W, b))

RMSE for training: 0.6776988339387257
RMSE for test    : 0.6588685357262771